// Midcodes - screengate
// version 0.0.1
//hi dear ilove you


// VIEWs and FUNCTIONS cant be done here

// ----  INDEX of TABLES  ----
// bio , bio_types
// authorized

// the admin can see all the logs
// the student can only input data thru the scanner
// teachers and employees have the same role
// contacts receive the notifcation or SMS
// contacts can see the history of notifications of their dependent
// devices

// -- IDEAL SCENARIO ---
//  scan - get bio data - get cont!c4

// *******  PHYSICAL SIDE ********** 
// main
Table bio {
  id serial [pk,unique]
  id_number varchar [not null, note:'This can be LRN , EID']
  picture varchar [note: 'File location']
  first_name varchar(50)
  middle_name varchar(50) 
  last_name varchar(50)
  suffix varchar(30)
  full_name varchar
  birthday date
  phone_number varchar 
  address varchar
  is_subscribed boolean [default: false]
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}
// one to one
Table student {
  id serial [pk]
  bio_id serial  [not null]
  grade_id serial [ note: 'changes every year']
}
// one to one
Table grade {
  id serial [pk]
  name varchar(50)
  created_at timestamp [default: `now()`]
}
// one to one
Table teacher {
  id serial [pk]
  bio_id serial  [not null]
  position varchar
  created_at timestamp [default: `now()`]
}
// one to one
Table employee {
  id serial [pk]
  bio_id serial  [not null]
  position varchar
  created_at timestamp [default: `now()`]
}
// one to one
Table parent {
  id serial [pk]
  bio_id serial  [not null]
  created_at timestamp [default: `now()`]
}
// one to one
Table guardian {
  id serial [pk]
  bio_id serial  [not null]
  created_at timestamp [default: `now()`]
}
// Creating references
// You can also define relaionship separately
// > many-to-one; < one-to-many; - one-to-one
Ref: bio.id - student.bio_id
Ref: bio.id - teacher.bio_id
Ref: bio.id - employee.bio_id
Ref: bio.id - parent.bio_id
Ref: bio.id - guardian.bio_id
Ref: student.grade_id > grade.id
