/// -- LEVEL 1
//// -- Tables and References
// **************  PHYSICAL SIDE ************** 
Enum user_types {
  student
  teacher
  employee
  admin
}


// ----  INDEX of TABLES  ----
// user , contact , gate , device , auth
// grade_level
// notification , scan , sms

// a contact can have many students
// gates can have many devices
// devices can have m


// the admin can see all the logs
// the student can only input data thru the scanner
// teachers and employees have the same role
// contacts receive the notifcation or SMS
// contacts can see the history of notifications of their dependent
// devices
Table authorized {
  username
  password
  email
}

Table person {
  id int [pk, increment] // auto-increment
  id_number varchar // LRN ID
  user_type user_types
  first_name varchar
  middle_name varchar
  last_name varchar
  suffix varchar
  full_name varchar
  birthday date
  validity varchar
  position 
  is_an_employee boolean

  phone_number varchar
  street

  created_at timestamp
  updated_at timestamp
}

Table contacts {
  // the student themself can be a contact
  // every person can be a contact
  id uuid
  name
  address
  relationship
  student_id [ref: > students.id]
  created_at
}

Table gates {

}

Table devices{

}
// **************  ABSTRACT SIDE ************** 

Table grade {
// has advisor/teacher
// has students
}
Table grade {
// has advisor
// has students
}


// **************  DIGITAL SIDE ************** 

Table notifications {
  id
  scanid int [not null, unique]
  contact_id
  notification_content  [note: 'When order created']
  created_at
}

Table scans {
  id
  scan int [ref: > orders.id]
  device
  gate
  designation boolean 
  created_at
  user_id
  contact_id
  created_at
  Indexes {
    (merchant_id, status) [name:'product_status']
    id [unique]
  }
}

Table sms_counter
{
  id
  smsc
  count
}

Table sms {
  id
  smsc
  to
  from
  status
  content
}

// Creating references
// You can also define relaionship separately
// > many-to-one; < one-to-many; - one-to-one
Ref: U.country_code > countries.code  
Ref: merchants.country_code > countries.code
